import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import {
  chmod,
  mkdir,
  readFile,
  readdir,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { promisify } from "node:util";
import {
  createTerminalRecordStore,
  terminalSandboxInstance,
  TERMINAL_RECORD_RETENTION_MS,
  type TerminalExecutionRecord,
} from "../terminal-execution-record";

const exec = promisify(execFile);
const roots: string[] = [];

async function fixture(
  options: {
    windows?: boolean;
    unavailable?: boolean;
    oldNode?: boolean;
    hook?: string;
  } = {},
) {
  const root = `/tmp/hackerai-retention-${randomUUID()}`;
  roots.push(root);
  await mkdir(root, { mode: 0o700 });
  const localPath = (name: string) =>
    name.replace("/tmp/terminal_execution_records", root);
  const responses: string[] = [];
  const commands = {
    run: jest.fn(async (command: string) => {
      // Map only the test's private record root; execute the production scanner
      // and the actual recovery schema generated by createTerminalRecordStore.
      const match = /'([A-Za-z0-9+/=]+)'; else/.exec(command)!;
      const input = JSON.parse(Buffer.from(match[1], "base64").toString());
      input.root = root;
      input.directory = localPath(input.directory);
      command = command.replace(
        match[1],
        Buffer.from(JSON.stringify(input)).toString("base64"),
      );
      if (options.hook) {
        const script = /Buffer.from\('([A-Za-z0-9+/=]+)'/.exec(command)![1];
        command = command.replace(
          script,
          Buffer.from(
            options.hook + Buffer.from(script, "base64").toString(),
          ).toString("base64"),
        );
      }
      if (options.oldNode) {
        command = command.replace(
          'node -e "',
          "node -e \"Object.defineProperty(process.versions, 'node', {value: '16.0.0'}); ",
        );
      }
      const { stdout } = await exec("/bin/bash", ["-c", command], {
        env: options.unavailable
          ? { ...process.env, PATH: "/nonexistent" }
          : process.env,
      });
      responses.push(stdout);
      return { stdout, stderr: "", exitCode: 0 };
    }),
  };
  const files = {
    write: jest.fn(async (name: string, value: string) =>
      writeFile(localPath(name), value),
    ),
    read: jest.fn(async (name: string) => readFile(localPath(name), "utf8")),
    list: jest.fn(async (name: string) =>
      (await readdir(localPath(name))).map((name) => ({ name })),
    ),
    remove: jest.fn(async (name: string) => rm(localPath(name))),
  };
  const sandbox = {
    sandboxKind: "centrifugo",
    isWindows: () => options.windows ?? false,
    supportsNativeFileRelay: () => true,
    getConnectionInfo: () => ({
      connectionId: "test-relay",
      environmentId: "test-installation",
      isDesktop: true,
    }),
    commands,
    files,
  } as any;
  const store = createTerminalRecordStore(sandbox, "test-user", randomUUID());
  const directory = localPath(store.pathFor("00000000")).replace(
    /\/[^/]+$/,
    "",
  );
  await mkdir(directory, { mode: 0o700 });
  const record = (
    session: string,
    overrides: Partial<TerminalExecutionRecord> = {},
  ): TerminalExecutionRecord => ({
    version: 1,
    session,
    sandboxInstance: terminalSandboxInstance(sandbox),
    command: "test command",
    pid: 123,
    status: "completed",
    exitCode: 0,
    exitReason: "process_exit",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    output: "saved evidence",
    outputTruncated: false,
    artifactPaths: ["/tmp/evidence"],
    ...overrides,
  });
  const put = async (
    session: string,
    overrides: Partial<TerminalExecutionRecord> = {},
  ) => {
    const value = JSON.stringify(record(session, overrides));
    await writeFile(localPath(store.pathFor(session)), value, { mode: 0o600 });
    return value;
  };
  return {
    root,
    directory,
    store,
    record,
    put,
    files,
    commands,
    responses,
    localPath,
  };
}

afterEach(async () => {
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
  );
});

describe("local terminal retention", () => {
  it.each([8, 64])(
    "retains and recovers %i full-output records without downloading them during pruning",
    async (count) => {
      const f = await fixture();
      let savedBytes = 0;
      for (let i = 0; i < count; i++) {
        savedBytes += Buffer.byteLength(
          await f.put(i.toString(16).padStart(8, "0"), {
            output: "x".repeat(262_144),
          }),
        );
      }
      await f.store.prune();
      expect(f.commands.run).toHaveBeenCalledTimes(1);
      expect(f.files.read).not.toHaveBeenCalled();
      expect(f.files.list).not.toHaveBeenCalled();
      expect(JSON.parse(f.responses[0])).toEqual({
        complete: true,
        scanned: count,
        removed: 0,
      });
      expect(Buffer.byteLength(f.responses[0])).toBeLessThan(100);
      expect(Buffer.byteLength(f.commands.run.mock.calls[0][0])).toBeLessThan(
        16_384,
      );
      expect(savedBytes).toBeGreaterThan(count * 262_144);
      expect(await readdir(f.directory)).toHaveLength(count);
      expect(await f.store.read("00000000")).toMatchObject({
        output: "x".repeat(262_144),
        status: "completed",
      });
      await f.store.prune();
      expect(f.commands.run).toHaveBeenCalledTimes(1);
    },
  );

  it("keeps the newest 64 valid records and removes seven-day-old records", async () => {
    const f = await fixture();
    const now = Date.now();
    for (let i = 0; i < 70; i++)
      await f.put(i.toString(16).padStart(8, "0"), {
        updatedAt: now - i * 1000,
      });
    await f.put("ffffffff", {
      updatedAt: now - TERMINAL_RECORD_RETENTION_MS - 1000,
    });
    await f.store.prune();
    expect(await readdir(f.directory)).toHaveLength(64);
    expect(await f.store.read("00000000")).not.toBeNull();
    expect(await f.store.read("0000003f")).not.toBeNull();
    expect(await f.store.read("00000040")).toBeNull();
    expect(JSON.parse(f.responses[0])).toEqual({
      complete: true,
      scanned: 71,
      removed: 7,
    });
  });

  it("preserves corrupt, foreign, mismatched, oversized, schema-invalid and symlinked records", async () => {
    const f = await fixture();
    const old = Date.now() - TERMINAL_RECORD_RETENTION_MS - 1000;
    const invalid = [
      { sandboxInstance: "another-installation" },
      { session: "aaaaaaaa" },
      { version: 2 },
      { pid: -1 },
      { pid: 1.5 },
      { status: "invented" },
      { output: "x".repeat(262_145) },
      { command: "x".repeat(32_769) },
      { workingDirectory: 1 },
      { exitCode: "0" },
      { exitReason: 123 },
      { outputTruncated: "false" },
      { artifactPaths: Array(33).fill("/tmp") },
    ];
    for (let i = 0; i < invalid.length; i++)
      await f.put(i.toString(16).padStart(8, "0"), {
        updatedAt: old,
        ...invalid[i],
      } as any);
    await writeFile(`${f.directory}/eeeeeeee.json`, "{");
    await writeFile(`${f.directory}/dddddddd.json`, " ".repeat(2_000_001));
    await f.put("cccccccc", { updatedAt: old });
    await symlink(
      `${f.directory}/cccccccc.json`,
      `${f.directory}/bbbbbbbb.json`,
    );
    await f.store.prune();
    expect(await readdir(f.directory)).toHaveLength(invalid.length + 3);
    expect(JSON.parse(f.responses[0])).toEqual({
      complete: true,
      scanned: 1,
      removed: 1,
    });
  });

  it("preserves a checkpoint replaced after scanning", async () => {
    const f = await fixture({
      hook: `
      const raceFs = require("node:fs");
      const originalLstat = raceFs.lstatSync;
      let reads = 0;
      raceFs.lstatSync = function(name, options) {
        if (name.endsWith("abcdef12.json") && ++reads === 2) {
          const record = JSON.parse(raceFs.readFileSync(name, "utf8"));
          record.updatedAt = Date.now(); record.output = "new checkpoint";
          raceFs.writeFileSync(name + ".tmp", JSON.stringify(record));
          raceFs.renameSync(name + ".tmp", name);
        }
        return originalLstat.call(this, name, options);
      };
    `,
    });
    await f.put("abcdef12", {
      updatedAt: Date.now() - TERMINAL_RECORD_RETENTION_MS - 1000,
    });
    await f.store.prune();
    expect(await f.store.read("abcdef12")).toMatchObject({
      output: "new checkpoint",
    });
    expect(JSON.parse(f.responses[0]).removed).toBe(0);
  });

  it("skips unsafe scopes without falling back to downloads", async () => {
    const f = await fixture();
    await f.put("abcdef12", { updatedAt: 0 });
    await chmod(f.directory, 0o777);
    await f.store.prune();
    expect(await readdir(f.directory)).toEqual(["abcdef12.json"]);
    expect(f.files.read).not.toHaveBeenCalled();
    expect(JSON.parse(f.responses[0])).toEqual({ complete: false });
  });

  it("preserves records if recovery adds an unsupported schema constraint", async () => {
    const f = await fixture({
      hook: `
        const changedInput = JSON.parse(Buffer.from(process.argv[1], "base64").toString());
        changedInput.schema.properties.output.minLength = 1;
        process.argv[1] = Buffer.from(JSON.stringify(changedInput)).toString("base64");
      `,
    });
    await f.put("abcdef12", { updatedAt: 0 });
    await f.store.prune();
    expect(await readdir(f.directory)).toEqual(["abcdef12.json"]);
    expect(JSON.parse(f.responses[0])).toEqual({ complete: false });
  });

  it("retains running records with nullable exit fields and optional working directory", async () => {
    const f = await fixture();
    await f.put("abcdef12", {
      status: "running",
      exitCode: null,
      exitReason: null,
      workingDirectory: "/tmp",
    });
    await f.store.prune();
    expect(JSON.parse(f.responses[0])).toEqual({
      complete: true,
      scanned: 1,
      removed: 0,
    });
    expect(await f.store.read("abcdef12")).toMatchObject({
      status: "running",
      exitCode: null,
    });
  });

  it.each([{ windows: true }, { unavailable: true }, { oldNode: true }])(
    "uses file APIs when the command fast path is unavailable: %j",
    async (options) => {
      const f = await fixture(options);
      await f.put("abcdef12", { updatedAt: 0 });
      await f.store.prune();
      expect(f.files.list).toHaveBeenCalledTimes(1);
      expect(f.files.read).toHaveBeenCalledTimes(1);
      expect(await readdir(f.directory)).toEqual([]);
    },
  );

  it("tolerates disconnects without deleting records or falling back to a bulk download", async () => {
    const f = await fixture();
    await f.put("abcdef12", { updatedAt: 0 });
    f.commands.run.mockRejectedValueOnce(new Error("disconnected"));
    await expect(f.store.prune()).resolves.toBeUndefined();
    expect(await readdir(f.directory)).toEqual(["abcdef12.json"]);
    expect(f.files.list).not.toHaveBeenCalled();
  });
});
